# -*- coding: utf-8 -*-
"""Aprendizado_mapquina_classificador_bin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10V6r8guV67zVUmmlE0uJGnnTsaxTDlqO
"""

import polars as pl
import numpy as np
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.svm import LinearSVC

pipeline = Pipeline([
    ("features", FeatureUnion([
        ("word", TfidfVectorizer(analyzer="word", ngram_range=(1,2), min_df=3)),
        ("char", TfidfVectorizer(analyzer="char", ngram_range=(1,5), min_df=3))
    ])),
    ("kbest", SelectKBest(chi2, k=22000)),
    ("clf", LinearSVC(C=0.9))
])

files = [
    "treino/train_arcaico_moderno.csv",
    "treino/train_complexo_simples.csv",
    "treino/train_literal_dinamico.csv",
]

for file in files:
  csv = pl.read_csv(source=file, separator=";").filter(pl.col("text").is_not_null())

  label_text = list(set(csv["style"]))
  labels = [0 if style == label_text[0] else 1 for style in csv["style"]]
  texts = [text for text in csv['text']]

  scores = cross_val_score(pipeline, texts, labels, cv=10, scoring="accuracy")

  print(f"\nArquivo: {file}")
  print(f"Acurácias por fold: {np.round(scores, 4)}")
  print(f"Acurácia média (10 folds): {np.mean(scores):.4f}")
